### ISSUE TITLE
Project page is inaccessible

### ISSUE THREAD

**Issue by justinwiley** [qoobaa/magic#5]
When following the link in the main readme.

Some basic instructions for how to use this gem for common tasks like determining filetype would be helpful. Edit: looks like there are some usage instructions in Rdoc with the Magic class

**Comment by qoobaa** [comment]
Thanks for pointing it out - the project definitely needs a `README`. I'll try to find time to make one. Feel free to submit a PR if you want to contribute.

**Comment by qoobaa** [comment]
Fixed.
